### PR TITLE
Added enviroment variables 

### PR DESCRIPTION
**Pull request by mezotv**

### CODE REVIEW

**Comment by kingstonv1** [comment]
Thank you, this seems like the better approach 👍

**Comment by mezotv** [comment]
If its the better approach why didn't you merge it?

**Comment by kingstonv1** [comment]
I'm not quite sure why the thread didn't mark the merge the first time, but it was merged in the repo nonetheless.
image

**Comment by kingstonv1** [comment]
you should be fine now anyways. Thank you

**Comment by mezotv** [comment]
Aight thanks!

**Pull request merged**
